version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: attendance
      MYSQL_USER: miu
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      - backbone
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    restart: always
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
