common:
  security:
    enabled: false
  feign-oauth:
    enabled: false
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
spring:
  security:
#    user:
#      name: miu
#      password: password

    oauth2:
      client:
        registration:
          google:
            client-id: 430488377001-985lu1m32oc2n1vqt1fhgdlj9auf8394.apps.googleusercontent.com
            client-secret: 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
  application:
    name: attendance-server
  datasource:
    url: jdbc:mysql://localhost:3307/attendance
    username: miu
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
  file:
    name: ./data/log/Logging/${spring.application.name}/logs

alert:
  msg:
    cron:
      job: 0/20 * * * * ?